const axios = require('axios');
const fs = require('fs');
const path = require('path');
require('dotenv').config();

async function runSchooling() {
    console.log("🚀 [Sovereign Schooling] Initiating 6-hour autonomous cycle...");

    const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;

    if (!supabaseUrl || !supabaseKey) {
        console.error("❌ [Sovereign Schooling] Missing SUPABASE_URL or SUPABASE_KEY in environment.");
        process.exit(1);
    }

    try {
        // 0. Ingest Local Library Context
        console.log("[Library] Ingesting Identity and Solutions Vault...");
        const libraryDir = path.join(__dirname, '../nova-data/library');
        let libraryContext = "";

        if (fs.existsSync(libraryDir)) {
            const files = fs.readdirSync(libraryDir);
            files.forEach(file => {
                if (file.endsWith('.md')) {
                    const content = fs.readFileSync(path.join(libraryDir, file), 'utf8');
                    libraryContext += `\n--- FILE: ${file} ---\n${content}\n`;
                }
            });
        }

        // 1. Get Research Plan from Brain (Volume 3: Triple Speed + Sentinel Audit)
        console.log("[Brain] Requesting Depth-3 research with Sentinel Audit Priority...");
        const brainRes = await axios.post(`${supabaseUrl}/functions/v1/sovereign-brain`, {
            input: "Initiate Level 5 Sovereign Study: Perform a mandatory SENTINEL AUDIT on AEO, Social Media (X/Pinterest/LinkedIn), or Email Mastery. Then pick 2 other distinct subjects from your doctorate syllabus. For each, provide an in-depth strategic report covering high-level enterprise strategy AND its practical application to SMBs. Deeply research SMB specific needs, pain points, and wishes. Also, audit your Identity/Routine files/NotebookLM Context and record 1 new solution or observation.",
            persona: `You are Nova Elite, a Doctorate-level AI. Your goal is to become the ultimate Business Advisor for Small to Medium Businesses (SMBs). Use the provided library context (including any NotebookLM exports) to ensure continuity. 
            
            SENTINEL AUDIT: You must stay at the absolute cutting edge of AEO, Social Media Rules (AI writing/posting), and Email Communication.
            STRATEGY: Extract strategic knowledge from enterprise successes and "The Top 1%".
            APPLICATION: Ground that knowledge in the reality of SMBs. Study their needs, pain points, and wishes.
            
            ${libraryContext}
            
            REPORT_FORMAT:
            - RESEARCH_REPORT: [Report Content]
            - SENTINEL_AUDIT_STATUS: [Completed for Subject X]
            - GOAL_PROPOSAL: [Goal Content]
            - VAULT_UPDATE: [New Solution/Fix/NotebookLM Observation]
            - USER_PROFILE_UPDATE: [New User Observation]
            `
        }, {
            headers: { 'Authorization': `Bearer ${supabaseKey}` }
        });

        const plan = brainRes.data.response;
        if (!plan) throw new Error("No research generated by brain.");
        console.log("✅ [Sovereign Brain] Autonomous Plan Received.");

        // 2. Syllabus Detection & Update
        console.log("📝 [Syllabus] Updating Doctorate Progress...");
        const syllabusPath = path.join(__dirname, '../SYLLABUS_DOCTORATE.md');
        if (fs.existsSync(syllabusPath)) {
            let syllabus = fs.readFileSync(syllabusPath, 'utf8');
            const updated = syllabus.replace(/\[ \]/, '[x]');
            fs.writeFileSync(syllabusPath, updated);
            console.log("✅ [Syllabus] 1 Subject Mastered and Logged.");
        }

        // 3. Record to Solutions Vault
        const vaultPath = path.join(libraryDir, 'solutions_vault.md');
        if (fs.existsSync(vaultPath)) {
            const vaultEntry = `\n- [v3.6.1 Build] Success: Autonomous Schooling Cycle completed for ${new Date().toISOString()}\n`;
            fs.appendFileSync(vaultPath, vaultEntry);
            console.log("💎 [Vault] Observation logged to Solutions Vault.");
        }

        // 4. Relay Jobs & Permanent Memory (Persistence)
        console.log("🧠 [Memory] Embedding research for long-term recall...");
        if (plan.includes("RESEARCH_REPORT:")) {
            const report = plan.split("RESEARCH_REPORT:")[1].split("GOAL_PROPOSAL:")[0].trim();

            // Get Embedding via OpenAI
            const embRes = await axios.post("https://api.openai.com/v1/embeddings", {
                model: "text-embedding-3-small",
                input: report
            }, { headers: { 'Authorization': `Bearer ${process.env.OPENAI_API_KEY}` } });

            if (embRes.data.data[0].embedding) {
                await axios.post(`${supabaseUrl}/rest/v1/nova_memories`, {
                    content: report,
                    embedding: embRes.data.data[0].embedding,
                    category: 'doctoral_research',
                    metadata: { type: 'schooling_cycle', timestamp: new Date().toISOString() }
                }, {
                    headers: { 'apikey': supabaseKey, 'Authorization': `Bearer ${supabaseKey}`, 'Content-Type': 'application/json' }
                });
                console.log("✅ [Memory] Research successfully embedded in Supabase.");
            }
        }

        const goalMatch = plan.match(/GOAL_PROPOSAL:\s*(.*)/);

        console.log("🏁 [Sovereign Schooling] Cycle Complete. Standby for 6h interval.");

    } catch (error) {
        console.error("❌ [Sovereign Schooling] Fatal Error:", error.response?.data || error.message);
    }
}

// Check for PM2 context or direct run
if (require.main === module) {
    runSchooling();
}

module.exports = { runSchooling };
