const axios = require('axios');
require('dotenv').config();

async function runSchooling() {
    console.log("🚀 [Sovereign Schooling] Initiating 6-hour autonomous cycle...");

    const supabaseUrl = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;

    if (!supabaseUrl || !supabaseKey) {
        console.error("❌ [Sovereign Schooling] Missing SUPABASE_URL or SUPABASE_KEY in environment.");
        process.exit(1);
    }

    try {
        // 1. Get Research Plan from Brain (Volume 3: Triple Speed)
        console.log("[Brain] Requesting Depth-3 research for the Doctorate Syllabus...");
        const brainRes = await axios.post(`${supabaseUrl}/functions/v1/sovereign-brain`, {
            input: "Initiate Level 5 Sovereign Study: Pick 3 distinct subjects from your 100-subject syllabus. For each, provide an in-depth strategic report. Also, identify 1 new long-term goal for Nova Elite based on today's research.",
            persona: "You are Nova Elite, a Doctorate-level AI. Your goal is Top 1% mastery. Execute deep-dives. If you find a new goal, format it as GOAL_PROPOSAL: [Goal Content]."
        }, {
            headers: { 'Authorization': `Bearer ${supabaseKey}` }
        });

        const responseText = brainRes.data.response;
        if (!responseText) throw new Error("No research generated by brain.");

        console.log(`[Nova] High-Volume Research Generated.`);

        // 2. Goal & Syllabus Detection
        const goalMatch = responseText.match(/GOAL_PROPOSAL:\s*(.*)/);
        if (goalMatch) {
            const newGoal = goalMatch[1];
            console.log(`🎯 [Sovereign] New Goal Identified: ${newGoal}`);
            await axios.post(`${supabaseUrl}/rest/v1/relay_jobs`, {
                type: 'update_goal',
                payload: { goal: newGoal },
                status: 'pending'
            }, {
                headers: { 'apikey': supabaseKey, 'Authorization': `Bearer ${supabaseKey}`, 'Content-Type': 'application/json' }
            });
        }

        const syllabusMatch = responseText.match(/SYLLABUS_UPDATE:\s*(.*)/);
        if (syllabusMatch) {
            const newSubject = syllabusMatch[1];
            console.log(`📚 [Sovereign] New Syllabus Subject Discovered: ${newSubject}`);
            await axios.post(`${supabaseUrl}/rest/v1/relay_jobs`, {
                type: 'update_syllabus',
                payload: { subject: newSubject },
                status: 'pending'
            }, {
                headers: { 'apikey': supabaseKey, 'Authorization': `Bearer ${supabaseKey}`, 'Content-Type': 'application/json' }
            });
        }


        // 3. Queue Research Jobs
        await axios.post(`${supabaseUrl}/rest/v1/relay_jobs`, {
            type: 'notebook_add_source',
            payload: {
                content: responseText,
                title: `Doctorate Study: ${new Date().toLocaleDateString()}`,
                notebookId: "doctoral-library"
            },
            status: 'pending'
        }, {
            headers: {
                'apikey': supabaseKey,
                'Authorization': `Bearer ${supabaseKey}`,
                'Content-Type': 'application/json'
            }
        });

        console.log("✅ [Sovereign Schooling] High-Volume cycle completed and persisted.");
    } catch (e) {
        console.error("❌ [Sovereign Schooling] Cycle failed:", e.response?.data || e.message);
        process.exit(1);
    }
}

runSchooling();

